# Generated by Django 4.1.3 on 2022-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('module_course', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
