# Generated by Django 4.1.3 on 2022-11-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_rename_model_id_style_academic_year_style_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='module_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
